Tidy bashrc files

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -7,72 +7,73 @@
 # PROMPT_COMMAND installer
 # usage: set_prompt_command 'history -a'
 function set_prompt_command () {
-	[ x"$1" == x ] && return
-	local new="$1"
+    [ x"$1" == x ] && return
+    local new="$1"
 
-	# Simply set if unset
-	if [[ x"$PROMPT_COMMAND" == x ]]; then
-		PROMPT_COMMAND="$new"
-		return
-	fi
+    # Simply set if unset
+    if [[ x"$PROMPT_COMMAND" == x ]]; then
+        PROMPT_COMMAND="$new"
+        return
+    fi
 
-	# Else, read the commands into an array
-	IFS=';' read -r -a cmds <<<"$PROMPT_COMMAND"
+    # Else, read the commands into an array
+    IFS=';' read -r -a cmds <<<"$PROMPT_COMMAND"
 
-	# Check if the command already exists
-	local set='false'
-	for cmd in "${cmds[@]}"; do
-		[[ "$cmd" == "$new" ]] && set='true'
-	done
+    # Check if the command already exists
+    local set='false'
+    for cmd in "${cmds[@]}"; do
+        [[ "$cmd" == "$new" ]] && set='true'
+    done
 
-	# Return if the command exists
-	if [[ "$set" == 'true' ]]; then
-		unset cmd cmds
-		return
-	# Else, append the new command
-	else
-		[[ "${PROMPT_COMMAND: -1}" == ';' ]] || new=";${new}"
-		export PROMPT_COMMAND="${PROMPT_COMMAND}${new}"
-	fi
+    # Return if the command exists
+    if [[ "$set" == 'true' ]]; then
+        unset cmd cmds
+        return
+    # Else, append the new command
+    else
+        [[ "${PROMPT_COMMAND: -1}" == ';' ]] || new=";${new}"
+        export PROMPT_COMMAND="${PROMPT_COMMAND}${new}"
+    fi
 }
 
 # Alias installer
 # usage: set_alias <key> <value>
 function set_alias () {
-	[ x"$1" == x ] && return
-	[ x"$2" == x ] && return
+    [ x"$1" == x ] && return
+    [ x"$2" == x ] && return
 
-	# We can ignore files
-	local type="$(type -t "$1")"
-	if [ -n "$type" ] && [ "$type" != 'file' ] ; then
-		>&2 printf 'String “%s” alredy exists as a %s\n' "$1" "$type"
-	else
-		alias "$1"="$2"
-	fi
+    # We can ignore files
+    local _type
+    _type="$(type -t "$1")"
+    if [ -n "$_type" ] && [ "$_type" != 'file' ] ; then
+        >&2 printf 'String “%s” already exists as a %s\n' "$1" "$_type"
+    else
+        alias "$1"="$2"
+    fi
 }
 
 # Archive extractor
 # usage: ex <file>
 function ex () {
-	if [ -f $1 ]; then
-		case $1 in
-		  *.tar.bz2)	tar xjf		"$1";;
-		  *.tar.gz)		tar xzf		"$1";;
-		  *.bz2)		bunzip2		"$1";;
-		  *.rar)		unrar x		"$1";;
-		  *.gz)			gunzip		"$1";;
-		  *.tar)		tar xf		"$1";;
-		  *.tbz2)		tar xjf		"$1";;
-		  *.tgz)		tar xzf 	"$1";;
-		  *.xz)			unxz 		"$1";;
-		  *.zip)		unzip		"$1";;
-		  *.Z)			uncompress	"$1";;
-		  *.7z)			7z x		"$1";;
-		  *)			printf 'cannot be extracted via ex(): “%s”\n' "$1" ;;
-		esac
-	else
-		printf 'not a valid file: “%s”\n' "$1"
-	fi
+    if [ -f $1 ]; then
+        case $1 in
+          *.tar.bz2)    tar xjf     "$1";;
+          *.tar.gz)     tar xzf     "$1";;
+          *.bz2)        bunzip2     "$1";;
+          *.rar)        unrar x     "$1";;
+          *.gz)         gunzip      "$1";;
+          *.tar)        tar xf      "$1";;
+          *.tbz2)       tar xjf     "$1";;
+          *.tgz)        tar xzf     "$1";;
+          *.xz)         unxz        "$1";;
+          *.zip)        unzip       "$1";;
+          *.Z)          uncompress  "$1";;
+          *.7z)         7z x        "$1";;
+          *)            printf 'cannot be extracted via ex(): “%s”\n' "$1" ;;
+        esac
+    else
+        printf 'not a valid file: “%s”\n' "$1"
+    fi
 }
 
 #############
@@ -106,5 +107,5 @@ set_alias 'll' 'ls -lah --color'
 # Setup #
 #########
 for rc in "${_BASH_DIR}"*.bash; do
-	source "$rc"
+    source "$rc"
 done
